### PR TITLE
:memo: Doxygen docs

### PR DESCRIPTION
**Pull request by Tugduoff**
Added docs using doxygen for the project.

### CODE REVIEW

**Review by tibaudlemaout — DISMISSED** [review]
Saw the result and it looks great :+1:

**Comment by Tugduoff** [comment]
It has been done ! You can now generate the doc using : doxygen doc/Doxyfile

**Review by tibaudlemaout — APPROVED** [review]
Seems good :+1:

**Review by C0Florent — APPROVED** [review]
Thanks for descibing the doc in config files instead of pushing the generated doc

**Pull request merged**
